name: transfer
version: '0.1'
summary: Transfer files using transfer.sh
description: |
  Simply run:

      $ transfer path/to/file
      https://transfer.sh/pQ0mG/file

grade: stable
confinement: strict
base: core

apps:
  transfer:
    command: transfer
    plugs: [network, home, removable-media]

parts:
  scripts:
    plugin: dump
    source: .
    stage-packages: [curl]
